In [30]:
#use to quit Engines
aspen.Close()
engine.quit()

In [24]:
#importing all the neccessary libraries
import win32com.client as win32
#import the matlab engine
import matlab.engine
import os
import pandas as pd
from DAC_helpers import obtain_ergun_pressure_inlet

In [25]:
#Start Aspen controlling session

#Start Aspen
aspen = win32.gencache.EnsureDispatch("Apwn.Document")
print("Aspen Engine started")

#start matlab engine and continue sesssion
engine = matlab.engine.start_matlab()
print("MATLAB Engine started")

#add path to allow for easy finding of matlab files
engine.addpath(r"C:\Users\User\Documents\MATLAB", nargout=0)


aspen_sim_path = r"C:\Users\User\Documents\AspenTech\Aspen Plus V14.0\DAC_simulation_V2.bkp"
#Load simulation file
aspen.InitFromFile2(aspen_sim_path)
print(f"Aspen Simulation file in path: {aspen_sim_path} loaded and Aspen plus application opened.")

#Make aspen visible
aspen.Visible = True

#Suppress dialog
aspen.SuppressDialogs = True

Aspen Engine started
MATLAB Engine started
Aspen Simulation file in path: C:\Users\User\Documents\AspenTech\Aspen Plus V14.0\DAC_simulation_V2.bkp loaded and Aspen plus application opened.

In [26]:
# Read in data frame of LHS values
df_simulation_inputs = pd.read_csv("DAC_optimal_inputs.csv")
print("Latin Hypercube Sampling Values read into DataFrame")

# Check if the path of the file with the simulation result exists
print("Checking for a DAC simulation results csv")
if os.path.exists("DAC_optimal_simulation_results_testing.csv"):
    df_simulation_results = pd.read_csv("DAC_optimal_simulation_results_testing.csv")
    print("Yes, DAC optimal simulation results csv exists")

    # store index of the simulation results data frame in a list
    completed_sim_results_indicies = df_simulation_results["sim_index"].to_list()


#If the path of the file with the simulation results does not exist, create it
else:
    #Create an empty data frame that will hold the simulation results
    df_simulation_results = pd.DataFrame()

    #create an empty list that will contain the indicies of completed simulation
    completed_sim_results_indicies = []

print(f" Simulation results exist for {len(completed_sim_results_indicies)} runs")

#Start for loop that runs through the rows in the df_simulation_inputs LHS values
for (index, row) in df_simulation_inputs.iterrows():
    
    #Check if the current index is in completed simulation indexes, skip and move to the next index if satisfied
    if index in completed_sim_results_indicies:
        #skip and move to the next index
        continue
    
    #Now on index that does not yet exist
    print(f"Preparing simulation for index {index}")
    
    #Re intitialize the simulation before inputing values and running simulation
    # Do this at the start of every loop
    aspen.Engine.Reinit()
    print("Re initialized Aspen simulation to clear existing iterations")

    print("Now writing values into the desired fields in Aspen plus")
    #Writing LHS variables into desired Aspen plus fields
    
    #Writing in the feed flow in kmol/hr of CaCO3
    caco3_feed_flow_rate = row["caco3_flow_rate [kmol/hr]"]
    aspen.Tree.FindNode(r"\Data\Streams\CACO3\Input\TOTFLOW\CISOLID").Value = caco3_feed_flow_rate

    #Writing in and setting calciner temperature
    calciner_temperature = row["calciner_temp [Deg C]"]
    aspen.Tree.FindNode(r"\Data\Blocks\CALCINER\Input\TEMP").Value = calciner_temperature
    
    # Writing in the feed flow of Water, water that flows into the Slaker.
    #This equals the flow rate of CaO (Which is the flow rate of CaCO3) + 0.001
    # flow rate of water into the slaker
    slaker_water_in = caco3_feed_flow_rate + 0.001
    #print(slaker_water_in)
    #writing to aspen
    aspen.Tree.FindNode(r"\Data\Streams\WATER\Input\TOTFLOW\MIXED").Value = slaker_water_in

    #feed flow of calcium hyroxide that flows out from slaker into the mixer
    caOH2_flow = caco3_feed_flow_rate

    #Calculate the flow rate of water into mixer to achieve the desired hydration moisture fraction
    #first read in the desired moisture fraction
    pellet_water_fraction = row["pellet_moisture_frac"]
    #flow rate of water into mixer
    mixer_water_in = ((pellet_water_fraction / 18.02 * (1 - pellet_water_fraction)) * caOH2_flow * 74.09) - 0.001
    #Now write the mixer water flow rate into the proper aspen plus field
    aspen.Tree.FindNode(r"\Data\Streams\WATER2\Input\TOTFLOW\MIXED").Value = mixer_water_in

    #Write in the flow rate of air into the desired blower field
    air_flow = row["air_mol_flow_rate [kmol/hr]"]
    # air_flow entering the blower
    aspen.Tree.FindNode(r"\Data\Streams\AIR\Input\TOTFLOW\MIXED").Value

    #Write in the vapor fraction of humidifier
    RH = row["RH_air"]
    # RH in humidifier, calculate the mole flow rate of water vapor that gives the desired humidity fraction
    vap_mol = ((RH / 18.02 * (1 - RH)) * air_flow* 28.97)


    # read in the flow rate of water vapor
    #use relative humidity to determine the moles of water vapor that gives the humidity
    aspen.Tree.FindNode(r"\Data\Streams\H2O-VAP\Input\TOTFLOW\MIXED").Value = vap_mol
    

    #Writing in the DAC temperature
    #Read in temperature of DAC unit from lhs
    DAC_temp = row["DAC_ambient_temp [Deg C]"]
    #write the value in aspen DAC unit
    #DAC_temp in DAC unit
    aspen.Tree.FindNode("\Data\Blocks\DAC-UNIT\Input\TEMP").Value = DAC_temp
    



    #RUNNING THE SIMULATION AFTER WRITING IN "MOST" OF THE DESIRED VARIABLES INTO ASPEN PLUS FIELD
    #RUNNING THE SIMULATION. THIS STAGE IS CRUCIAL FOR THE HANDSHAKE BETWEEN MATLAB AND ASPEN PLUS
    #RUNNING THE SIMULATION. SOME VALUES WILL BE EXTRACTED FROM SOME ASPEN RESULTS FIELDS AND USED IN MATLAB SCM AND ERGUN PRESSURE DROP COMP.
    #RUNNING THE SIMULATION. PRODEEDS

    try:
        #This runs the aspen plus simulation
        aspen.Engine.Run2()
        print("Running Aspen plus simulation, trial 1/2")

        #Check the status of the simulation before grabbing results to see if the simulation converged. 0 is success
        convergence_status = aspen.Tree.FindNode(r"\Data\Results Summary\Run-Status\Output\PER_ERROR").Value
        if (convergence_status == 0) or (convergence_status==1):
            #Grab the reults immediately
            #Grab the volumetric flow rates of the pellets read in s litre/min. convert to m3/hr
            pellet_vol_flow = aspen.Tree.FindNode(r"\Data\Streams\PELLET\Output\RES_VOLFLOW").Value / 60000
            
            #Grab the results of the molecular weight of air 
            MW_air = aspen.Tree.FindNode(r"\Data\Streams\WET-AIR\Output\MW").Value
            
            #Grab the results of the volumetric flow rate of air leaving the humidifer and entering the DAC unit in l/mins. convert to m3/hr
            air_vol_flow_rate = aspen.Tree.FindNode(r"\Data\Streams\WET-AIR\Output\RES_VOLFLOW").Value / 60000

            #Read in the mass flow rate of wet air entering the DAC unit
            air_kg_per_hr = aspen.Tree.FindNode(r"\Data\Streams\WET-AIR\Output\RES_MASSFLOW").Value
            
            #Read in the mole fraction of co2 in air leaving humidifier and entering DAC unit
            y_co2 = aspen.Tree.FindNode(r"\Data\Streams\WET-AIR\Output\MOLEFRAC\MIXED\CO2").Value

            #Read in temperature of DAC unit from lhs
            DAC_temp = row["DAC_ambient_temp [Deg C]"]

            #Read in length of pipe from lhs
            height_DAC = row["DAC_column_height [m]"]

            #Read in the value of the voidage
            e_void = row["e_voidage"]

            #Read in the diameters of pellet from lhs
            pellet_diameter = pellet_diameter = row["pellet_diameter [mm]"]

            #Mole of CO2 into the DAC unit from the humidifier
            nco2 = aspen.Tree.FindNode(r"\Data\Streams\WET-AIR\Output\MOLEFLOW\MIXED\CO2").Value
            

            #Compute the Ergun pressue Inlet
            P_in_DAC =  obtain_ergun_pressure_inlet(L=height_DAC, e_void=e_void, dp=pellet_diameter, DAC_ambient_temp=DAC_temp, kg_per_hr=air_kg_per_hr, MW_air=MW_air)

            L= height_DAC
            npell= aspen.Tree.FindNode(r"\Data\Streams\PELLET\Output\MOLEFLMX\CISOLID").Value
            Vpell = pellet_vol_flow
            #Average pressure in the DAC unit. To be used MATLAB SCM
            P_ave = (2/3) * (P_in_DAC**2 + 1**2 + P_in_DAC * 1) / (P_in_DAC + 1)

            
            #MATLAB AND ASPEN PLUS HANDSHAKE. PYTHON SENDS VALUES TO MATLAB, MATLAB COMPUTES CONVERSION
            #MATLAB THEN SENDS CONVERSION TO PYTHON
            #PYTHON THEN WRITES THE CONVERSION INTO ASPEN AND RUNS THE SIMULATION THE SECOND TIME
            #RUN MATLAB ENGINE
            
            x_conversion, x_conv_pell = engine.DAC_func(matlab.double(pellet_diameter*0.001), matlab.double(y_co2), matlab.double(P_ave*101325), matlab.double(DAC_temp+273.15), matlab.double(RH), matlab.double(e_void), matlab.double(Vpell), matlab.double(L), matlab.double(npell), matlab.double(nco2), nargout=2)


            #print("MATLAB SIMULATION COMPLETED")

            #Write conversion into Aspen field
            aspen.Tree.FindNode(r"\Data\Blocks\DAC-UNIT\Input\CONV\1").Value = x_conversion

            #Set the pressure of pump and air blower equal to P_in_DAC
            # discharge presure of Air Blower unit
            aspen.Tree.FindNode(r"\Data\Blocks\AIR-BLOW\Input\PRES").Value = P_in_DAC
            
            # setting the inlet presusure of steam unit
            aspen.Tree.FindNode(r"\Data\Streams\H2O-VAP\Input\PRES\MIXED").Value = P_in_DAC

            ##RUN THE SECOND TRIAL OF SIMULATION
            ##RUN THE SECOND TRIAL OF SIMULATION
            ##RUN THE SECOND TRIAL OF SIMULATION
            ##RUN THE SECOND TRIAL OF SIMULATION
            ##RUN THE SECOND TRIAL OF SIMULATION
            ##RUN THE SECOND TRIAL OF SIMULATION
            ##RUN THE SECOND TRIAL OF SIMULATION
            
            aspen.Engine.Run2()
            print("Running Aspen plus simulation, trial 2/2")
            
            #Read the mass flow rate of co2 leaving the DAC unit
            #mass flow of co2 leaving the DAC unit
            mass_flow_co2_out = aspen.Tree.FindNode(r"\Data\Streams\CO2-LEAN\Output\MASSFLOW\MIXED\CO2").Value

            #Read in the mass flow rate of co2 into the DAC unit
            mass_flow_co2_in = aspen.Tree.FindNode(r"\Data\Streams\WET-AIR\Output\MASSFLOW\MIXED\CO2").Value

            #Read in the pellet flow rate
            calcium_hydroxide_pellet_kmol_per_hr = aspen.Tree.FindNode(r"\Data\Streams\PELLET\Output\RES_MOLEFLOW").Value

            #Read in the heat duty or work for each block
            E_duty_calciner = aspen.Tree.FindNode(r"\Data\Blocks\CALCINER\Output\QNET").Value

            #Slaker heat management cost is negligible
            #E_duty_slaker = aspen.Tree.FindNode(r"\Data\Blocks\SLAKER\Output\QNET").Value

            #Humidifier has negligible heat duty
            #E_duty_humidifier = aspen.Tree.FindNode(r"\Data\Blocks\HUMIDIFY\Output\QNET").Value

            #E_duty_DAC_unit = aspen.Tree.FindNode(r"\Data\Blocks\DAC-UNIT\Output\QNET").Value

            E_brake_air_blower = aspen.Tree.FindNode(r"\Data\Blocks\AIR-BLOW\Output\BRAKE_POWER").Value

            #K is a heat reintegration constant, obtained observation the heat duty required to raise a kmol/hr of caco3 to 450C.
            #Helps to estimate the heat from DAC unit that can be reintegrated back to the calciner

            k = 3.4746e-4


            #calculate total heat duty
            E_duty = abs(E_duty_calciner) - (caco3_feed_flow_rate / k)

            #calculate the total brake power
            E_brake_power = E_brake_air_blower


            #include results in current dictionary of results, first sure make to include the rows in the lhs
            curr_results = row.to_dict()

            curr_results["Simulation_status"] = "Success"
            curr_results["Failure_reason"] = None
            
            curr_results["Heat_duty[cal/sec]"] = E_duty
            curr_results["Brake_power[kW]"] = E_brake_power

            curr_results["calcium_hydroxide_pellet[kmol_per_hr]"] = calcium_hydroxide_pellet_kmol_per_hr

            curr_results["SCM_conversion_fraction"] = x_conversion
            curr_results["Ca(OH)2_conversion"] = x_conv_pell

            curr_results["mass_flow_co2_in[kg/hr]"] = mass_flow_co2_in

            curr_results["mass_flow_co2_out[kg/hr]"] = mass_flow_co2_out

            curr_results["DAC_inlet_press[atm]"] = P_in_DAC

            print(f"completed simulation run for simulation {index}")


            #convert to data frame
            df_current =  pd.DataFrame([curr_results])

            header_needed = not os.path.exists("DAC_optimal_simulation_results_testing.csv")

            #Append the data frame to
            df_current.to_csv("DAC_optimal_simulation_results_testing.csv", mode='a', index=False, header=header_needed)
            print("Added result of current simulation run to the DAC Simulation csv file")
            
    
        else:
            print("Aspen plus simulation trial 1/2 did NOT converge successfully")
            #include results in current dictionary of results, first sure make to include the rows in the lhs
            curr_results = row.to_dict()

            curr_results["Simulation_status"] = "Failure"
            curr_results["Failure_reason"] = "Simulation did not converge"
            curr_results["Ca(OH)2_conversion"] = None
            
            curr_results["Heat_duty[cal/sec]"] = None
            
            curr_results["Brake_power[kW]"] = None
            
            curr_results["calcium_hydroxide_pellet[kmol_per_hr]"] = None

            curr_results["SCM_conversion_fraction"] = None

            curr_results["mass_flow_co2_in[kg/hr]"] = None

            curr_results["mass_flow_co2_out[kg/hr]"] = None

            curr_results["DAC_inlet_press[atm]"] = None


            #convert to data frame
            df_current =  pd.DataFrame([curr_results])

            header_needed = not os.path.exists("DAC_optimal_simulation_results_testing.csv")

            #Append the data frame to
            df_current.to_csv("DAC_optimal_simulation_results_testing.csv", mode='a', index=False, header=header_needed)

            
            

        
    except Exception as e:
        
        print("Aspen plus simulation trial 1/2 did NOT converge successfully")
        #include results in current dictionary of results, first sure make to include the rows in the lhs
        curr_results = row.to_dict()

        curr_results["Simulation_status"] = "Failure"
        curr_results["Failure_reason"] = str(e)
            
        curr_results["Heat_duty[cal/sec]"] = None
        curr_results["Brake_power[kW]"] = None

        curr_results["SCM_conversion_fraction"] = None
        
        curr_results["calcium_hydroxide_pellet[kmol_per_hr]"] = None
        
        curr_results["Ca(OH)2_conversion"] = None

        curr_results["mass_flow_co2_in[kg/hr]"] = None

        curr_results["mass_flow_co2_out[kg/hr]"] = None

        curr_results["DAC_inlet_press[atm]"] = None


        #convert to data frame
        df_current =  pd.DataFrame([curr_results])

        header_needed = not os.path.exists("DAC_optimal_simulation_results_testing.csv")

        #Append the data frame to
        df_current.to_csv("DAC_optimal_simulation_results_testing.csv", mode='a', index=False, header=header_needed) #this line
        
        print(e)
print("all Simulations completed successfully")
aspen.Close()
engine.quit()

Latin Hypercube Sampling Values read into DataFrame
Checking for a DAC simulation results csv
 Simulation results exist for 0 runs
Preparing simulation for index 0
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 0
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 1
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 1
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 2
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 2
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 3
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 3
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 4
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 4
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 5
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 5
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 6
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 6
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 7
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Aspen plus simulation trial 1/2 did NOT converge successfully
(-2147352567, 'Exception occurred.', (14, 'VASetValue (see errcode)', 'Value is out of range; it must be between 0 and 1', None, 0, 0), None)
Preparing simulation for index 8
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 8
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 9
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 9
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 10
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 10
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 11
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Aspen plus simulation trial 1/2 did NOT converge successfully
(-2147352567, 'Exception occurred.', (14, 'VASetValue (see errcode)', 'Value is out of range; it must be between 0 and 1', None, 0, 0), None)
Preparing simulation for index 12
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 12
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 13
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 13
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 14
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 14
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 15
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 15
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 16
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Aspen plus simulation trial 1/2 did NOT converge successfully
(-2147352567, 'Exception occurred.', (14, 'VASetValue (see errcode)', 'Value is out of range; it must be between 0 and 1', None, 0, 0), None)
Preparing simulation for index 17
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Aspen plus simulation trial 1/2 did NOT converge successfully
(-2147352567, 'Exception occurred.', (14, 'VASetValue (see errcode)', 'Value is out of range; it must be between 0 and 1', None, 0, 0), None)
Preparing simulation for index 18
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Aspen plus simulation trial 1/2 did NOT converge successfully
(-2147352567, 'Exception occurred.', (14, 'VASetValue (see errcode)', 'Value is out of range; it must be between 0 and 1', None, 0, 0), None)
Preparing simulation for index 19
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Aspen plus simulation trial 1/2 did NOT converge successfully
(-2147352567, 'Exception occurred.', (14, 'VASetValue (see errcode)', 'Value is out of range; it must be between 0 and 1', None, 0, 0), None)
Preparing simulation for index 20
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 20
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 21
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 21
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 22
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 22
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 23
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 23
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 24
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 24
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 25
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 25
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 26
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 26
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 27
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Aspen plus simulation trial 1/2 did NOT converge successfully
(-2147352567, 'Exception occurred.', (14, 'VASetValue (see errcode)', 'Value is out of range; it must be between 0 and 1', None, 0, 0), None)
Preparing simulation for index 28
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Aspen plus simulation trial 1/2 did NOT converge successfully
(-2147352567, 'Exception occurred.', (14, 'VASetValue (see errcode)', 'Value is out of range; it must be between 0 and 1', None, 0, 0), None)
Preparing simulation for index 29
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 29
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 30
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 30
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 31
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Aspen plus simulation trial 1/2 did NOT converge successfully
(-2147352567, 'Exception occurred.', (14, 'VASetValue (see errcode)', 'Value is out of range; it must be between 0 and 1', None, 0, 0), None)
Preparing simulation for index 32
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 32
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 33
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Aspen plus simulation trial 1/2 did NOT converge successfully
(-2147352567, 'Exception occurred.', (14, 'VASetValue (see errcode)', 'Value is out of range; it must be between 0 and 1', None, 0, 0), None)
Preparing simulation for index 34
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 34
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 35
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 35
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 36
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Aspen plus simulation trial 1/2 did NOT converge successfully
(-2147352567, 'Exception occurred.', (14, 'VASetValue (see errcode)', 'Value is out of range; it must be between 0 and 1', None, 0, 0), None)
Preparing simulation for index 37
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 37
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 38
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Aspen plus simulation trial 1/2 did NOT converge successfully
(-2147352567, 'Exception occurred.', (14, 'VASetValue (see errcode)', 'Value is out of range; it must be between 0 and 1', None, 0, 0), None)
Preparing simulation for index 39
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Aspen plus simulation trial 1/2 did NOT converge successfully
(-2147352567, 'Exception occurred.', (14, 'VASetValue (see errcode)', 'Value is out of range; it must be between 0 and 1', None, 0, 0), None)
Preparing simulation for index 40
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Aspen plus simulation trial 1/2 did NOT converge successfully
(-2147352567, 'Exception occurred.', (14, 'VASetValue (see errcode)', 'Value is out of range; it must be between 0 and 1', None, 0, 0), None)
Preparing simulation for index 41
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 41
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 42
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 42
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 43
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Aspen plus simulation trial 1/2 did NOT converge successfully
(-2147352567, 'Exception occurred.', (14, 'VASetValue (see errcode)', 'Value is out of range; it must be between 0 and 1', None, 0, 0), None)
Preparing simulation for index 44
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 44
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 45
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 45
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 46
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Aspen plus simulation trial 1/2 did NOT converge successfully
(-2147352567, 'Exception occurred.', (14, 'VASetValue (see errcode)', 'Value is out of range; it must be between 0 and 1', None, 0, 0), None)
Preparing simulation for index 47
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 47
Added result of current simulation run to the DAC Simulation csv file
Preparing simulation for index 48
Re initialized Aspen simulation to clear existing iterations
Now writing values into the desired fields in Aspen plus
Running Aspen plus simulation, trial 1/2
Running Aspen plus simulation, trial 2/2
completed simulation run for simulation 48
Added result of current simulation run to the DAC Simulation csv file
all Simulations completed successfully

In [27]:
pd.read_csv("DAC_optimal_inputs.csv")

,caco3_flow_rate [kmol/hr],calciner_temp [Deg C],pellet_moisture_frac,air_mol_flow_rate [kmol/hr],RH_air,DAC_column_height [m],pellet_diameter [mm],DAC_ambient_temp [Deg C],e_voidage,capture_efficiency_%,SECC_$
0,97.863788,919.904840,0.064531,7118.821754,0.870483,9.997187,1.049191,42.714769,0.353125,65.621880,10.950542
1,97.924051,919.904840,0.064555,7118.821754,0.870483,9.997187,1.049191,42.716989,0.353125,65.621880,10.950542
2,97.832777,919.696195,0.064504,7117.219329,0.872091,9.999902,1.059883,43.707146,0.353171,65.603966,7.172618
3,97.837663,919.099393,0.064516,7114.636077,0.870726,9.995373,1.059244,43.733019,0.353064,65.585068,5.621132
4,97.898044,919.696195,0.064609,7045.451161,0.870730,9.995326,1.060114,43.722263,0.353059,65.578468,3.874981
5,97.621017,919.402894,0.065140,7041.773748,0.872018,9.996710,1.045518,43.740941,0.353145,65.559578,2.323490
6,97.806708,919.733927,0.064599,7117.490152,0.870721,9.999612,1.057005,43.717158,0.353101,65.603966,7.172618
7,97.667482,919.694791,0.064772,7042.829655,0.898222,9.966109,1.047911,43.729616,0.353064,65.494453,1.046576
8,97.904062,919.841700,0.064597,7044.707805,0.870339,9.999844,1.060147,43.717158,0.353101,65.578468,3.874981
9,97.837736,919.099393,0.064516,7105.147999,0.870726,9.995367,1.059244,43.733019,0.353064,65.585068,5.621132
10,97.661308,918.628331,0.064877,7039.763823,0.871076,9.987834,1.047763,43.785006,0.353091,65.503227,2.123235
11,97.759441,919.812692,0.064790,7042.829655,0.897805,9.945287,1.054384,43.731357,0.353062,65.494453,1.046576
12,97.621017,919.402894,0.065140,7041.740270,0.869943,9.996710,1.047230,43.695651,0.353169,65.559578,2.323490
13,97.662447,918.628331,0.064877,7043.944915,0.871076,9.987834,1.047763,43.697806,0.353091,65.503227,2.123235
14,97.900004,919.696195,0.064789,7044.456822,0.871572,9.998944,1.050015,43.720101,0.352963,65.578468,3.874981
15,97.854313,919.751345,0.064877,7039.593807,0.871076,9.983856,1.047763,43.785006,0.353083,65.578468,3.874981
16,97.673296,919.694791,0.065382,7041.851832,0.890512,9.999878,1.047911,43.713115,0.352965,65.494453,1.046576
17,97.665241,919.694791,0.064772,7042.829655,0.891756,9.989473,1.047911,43.729616,0.353064,65.494453,1.046576
18,97.813986,919.809207,0.065368,7043.188324,0.897852,9.995398,1.055331,43.733495,0.352967,65.494453,1.046576
19,97.820916,919.863916,0.064790,7042.829655,0.897013,9.997210,1.054059,43.732585,0.353064,65.494453,1.046576
20,97.901892,919.696195,0.064609,7114.497424,0.871012,9.999461,1.060168,43.719454,0.353059,65.603966,7.172618
21,97.901892,919.414385,0.064580,7114.497424,0.870730,9.998845,1.060193,43.722207,0.353059,65.585068,5.621132
22,97.901892,919.696195,0.064609,7114.497424,0.870730,9.999461,1.060119,43.722207,0.353059,65.603966,7.172618
23,97.893037,919.904000,0.065374,7044.449457,0.871572,9.999346,1.049415,43.763339,0.353123,65.578468,3.874981
24,97.665241,919.694791,0.064772,7042.829655,0.891756,9.927425,1.047911,43.729616,0.353064,65.494453,1.046576
25,97.928318,919.696195,0.064504,7114.497424,0.872029,9.999902,1.059883,43.706606,0.353171,65.603966,7.172618
26,97.904062,919.696195,0.064597,7117.490152,0.870721,9.999844,1.059018,43.717109,0.352897,65.603966,7.172618
27,97.667482,919.694791,0.065382,7041.851832,0.890512,9.999895,1.047911,43.768128,0.352965,65.494453,1.046576
28,97.621017,919.684704,0.064610,7041.773748,0.891618,9.991159,1.048967,43.740941,0.352969,65.494453,1.046576
29,97.621017,919.402894,0.065140,7113.550410,0.869943,9.996710,1.047753,43.707134,0.353145,65.585068,5.621132
30,97.660138,919.844301,0.064794,7042.829655,0.898967,9.938770,1.059125,43.755474,0.353054,65.494453,1.046576
31,97.667482,919.694791,0.064480,7042.829655,0.898210,9.974000,1.048218,43.729616,0.353064,65.494453,1.046576
32,97.903035,919.463633,0.064597,7114.497424,0.870721,9.999461,1.060119,43.717158,0.353101,65.585068,5.621132
33,97.896816,919.696169,0.064772,7042.829655,0.893056,9.921065,1.047859,43.729616,0.353064,65.494453,1.046576
34,97.890368,918.531637,0.064815,7042.814690,0.871627,9.999770,1.061477,43.718209,0.353157,65.503227,2.123235
35,97.924051,919.904840,0.064531,7118.821754,0.870483,9.997187,1.049191,42.714769,0.353125,65.621880,10.950542
36,97.855375,919.694791,0.064425,7042.949034,0.898374,9.998186,1.049956,43.754098,0.353064,65.494453,1.046576
37,97.660138,919.844301,0.064776,7042.829655,0.898871,9.946523,1.059125,43.713604,0.353066,65.494453,1.046576
38,97.669876,919.694791,0.065410,7043.317167,0.899325,9.995369,1.055556,43.769641,0.352992,65.494453,1.046576
39,97.660138,919.694791,0.064772,7042.829655,0.891951,9.946379,1.047911,43.729529,0.353066,65.494453,1.046576
40,97.830803,919.863916,0.064370,7042.829548,0.897022,9.996172,1.052508,43.740216,0.353020,65.494453,1.046576
41,97.610214,919.696195,0.064609,7114.497424,0.870730,9.999563,1.060119,43.722150,0.353059,65.603966,7.172618
42,97.777095,919.718626,0.064437,7120.039009,0.871542,9.968315,1.045678,43.752803,0.353181,65.603966,7.172618
43,97.621017,919.684704,0.064610,7041.773748,0.899617,9.991159,1.048967,43.740941,0.352969,65.494453,1.046576
44,97.893037,919.904000,0.065374,7044.449457,0.871572,9.999346,1.049415,43.763470,0.353123,65.578468,3.874981
45,97.904062,919.696195,0.064597,7117.490152,0.870721,9.999844,1.060147,43.717158,0.353101,65.603966,7.172618
46,97.815629,919.812692,0.064790,7042.829655,0.897819,9.944934,1.054384,43.731357,0.353062,65.494453,1.046576
47,97.893037,919.696195,0.065374,7044.449457,0.871572,9.999112,1.049415,43.763470,0.353059,65.578468,3.874981
48,97.901892,919.696195,0.064615,7040.245477,0.897293,9.986322,1.060145,43.774832,0.353059,65.494453,1.046576

In [28]:
pd.read_csv("DAC_optimal_simulation_results_testing.csv")

,caco3_flow_rate [kmol/hr],calciner_temp [Deg C],pellet_moisture_frac,air_mol_flow_rate [kmol/hr],RH_air,DAC_column_height [m],pellet_diameter [mm],DAC_ambient_temp [Deg C],e_voidage,capture_efficiency_%,...,Simulation_status,Failure_reason,Heat_duty[cal/sec],Brake_power[kW],calcium_hydroxide_pellet[kmol_per_hr],SCM_conversion_fraction,Ca(OH)2_conversion,mass_flow_co2_in[kg/hr],mass_flow_co2_out[kg/hr],DAC_inlet_press[atm]
0,97.863788,919.904840,0.064531,7118.821754,0.870483,9.997187,1.049191,42.714769,0.353125,65.621880,...,Success,NaN,1.457212e+06,17913.0026,122.153747,0.976727,0.029466,129.933354,3.023947,4.742487
1,97.924051,919.904840,0.064555,7118.821754,0.870483,9.997187,1.049191,42.716989,0.353125,65.621880,...,Success,NaN,1.458110e+06,17913.0905,122.237356,0.976974,0.029455,129.933354,2.991797,4.742516
2,97.832777,919.696195,0.064504,7117.219329,0.872091,9.999902,1.059883,43.707146,0.353171,65.603966,...,Success,NaN,1.456600e+06,17828.4877,122.105594,0.964936,0.029120,129.933354,4.555988,4.714537
3,97.837663,919.099393,0.064516,7114.636077,0.870726,9.995373,1.059244,43.733019,0.353064,65.585068,...,Success,NaN,1.456242e+06,17851.8849,122.115774,0.963974,0.029089,129.933354,4.681037,4.722263
4,97.898044,919.696195,0.064609,7045.451161,0.870730,9.995326,1.060114,43.722263,0.353059,65.578468,...,Success,NaN,1.457572e+06,17830.2229,122.223889,0.963410,0.029054,129.933354,4.754213,4.715110
5,97.621017,919.402894,0.065140,7041.773748,0.872018,9.996710,1.045518,43.740941,0.353145,65.559578,...,Success,NaN,1.453236e+06,17942.9735,122.063365,0.981104,0.029672,129.933354,2.455183,4.752427
6,97.806708,919.733927,0.064599,7117.490152,0.870721,9.999612,1.057005,43.717158,0.353101,65.603966,...,Success,NaN,1.456239e+06,17872.1426,122.106236,0.966676,0.029180,129.933354,4.329906,4.728959
7,97.667482,919.694791,0.064772,7042.829655,0.898222,9.966109,1.047911,43.729616,0.353064,65.494453,...,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,97.904062,919.841700,0.064597,7044.707805,0.870339,9.999844,1.060147,43.717158,0.353101,65.578468,...,Success,NaN,1.457766e+06,17833.3703,122.227054,0.963125,0.029044,129.933354,4.791345,4.716149
9,97.837736,919.099393,0.064516,7105.147999,0.870726,9.995367,1.059244,43.733019,0.353064,65.585068,...,Success,NaN,1.456243e+06,17849.9712,122.115865,0.964012,0.029090,129.933354,4.676003,4.721631
10,97.661308,918.628331,0.064877,7039.763823,0.871076,9.987834,1.047763,43.785006,0.353091,65.503227,...,Success,NaN,1.453278e+06,17930.2973,122.021679,0.976983,0.029535,129.933354,2.990637,4.748221
11,97.759441,919.812692,0.064790,7042.829655,0.897805,9.945287,1.054384,43.731357,0.353062,65.494453,...,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,97.621017,919.402894,0.065140,7041.740270,0.869943,9.996710,1.047230,43.695651,0.353169,65.559578,...,Success,NaN,1.453236e+06,17944.0152,122.063365,0.976238,0.029525,129.933354,3.087536,4.752772
13,97.662447,918.628331,0.064877,7043.944915,0.871076,9.987834,1.047763,43.697806,0.353091,65.503227,...,Success,NaN,1.453295e+06,17928.7074,122.023103,0.977034,0.029536,129.933354,2.984099,4.747693
14,97.900004,919.696195,0.064789,7044.456822,0.871572,9.998944,1.050015,43.720101,0.352963,65.578468,...,Success,NaN,1.457601e+06,17921.4791,122.289154,0.977312,0.029473,129.933354,2.947949,4.745296
15,97.854313,919.751345,0.064877,7039.593807,0.871076,9.983856,1.047763,43.785006,0.353083,65.578468,...,Success,NaN,1.456960e+06,17928.1236,122.262827,0.977568,0.029494,129.933354,2.914636,4.747500
16,97.673296,919.694791,0.065382,7041.851832,0.890512,9.999878,1.047911,43.713115,0.352965,65.494453,...,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,97.665241,919.694791,0.064772,7042.829655,0.891756,9.989473,1.047911,43.729616,0.353064,65.494453,...,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,97.813986,919.809207,0.065368,7043.188324,0.897852,9.995398,1.055331,43.733495,0.352967,65.494453,...,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,97.820916,919.863916,0.064790,7042.829655,0.897013,9.997210,1.054059,43.732585,0.353064,65.494453,...,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,97.901892,919.696195,0.064609,7114.497424,0.871012,9.999461,1.060168,43.719454,0.353059,65.603966,...,Success,NaN,1.457629e+06,17843.7386,122.228693,0.963759,0.029064,129.933354,4.708931,4.719572
21,97.901892,919.414385,0.064580,7114.497424,0.870730,9.998845,1.060193,43.722207,0.353059,65.585068,...,Success,NaN,1.457426e+06,17845.8292,122.218341,0.963347,0.029051,129.933354,4.762480,4.720262
22,97.901892,919.696195,0.064609,7114.497424,0.870730,9.999461,1.060119,43.722207,0.353059,65.603966,...,Success,NaN,1.457629e+06,17846.9058,122.228693,0.963457,0.029054,129.933354,4.748208,4.720618
23,97.893037,919.904000,0.065374,7044.449457,0.871572,9.999346,1.049415,43.763339,0.353123,65.578468,...,Success,NaN,1.457647e+06,17916.6817,122.485379,0.976936,0.029464,129.933354,2.996777,4.743706
24,97.665241,919.694791,0.064772,7042.829655,0.891756,9.927425,1.047911,43.729616,0.353064,65.494453,...,Success,NaN,1.454105e+06,17688.3767,121.989974,0.999235,0.030206,129.933354,0.099452,4.668465
25,97.928318,919.696195,0.064504,7114.497424,0.872029,9.999902,1.059883,43.706606,0.353171,65.603966,...,Success,NaN,1.458023e+06,17828.5164,122.224841,0.965291,0.029102,129.933354,4.509831,4.714547
26,97.904062,919.696195,0.064597,7117.490152,0.870721,9.999844,1.059018,43.717109,0.352897,65.603966,...,Success,NaN,1.457661e+06,17869.2144,122.227054,0.965362,0.029111,129.933354,4.500631,4.727991
27,97.667482,919.694791,0.065382,7041.851832,0.890512,9.999895,1.047911,43.768128,0.352965,65.494453,...,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,97.621017,919.684704,0.064610,7041.773748,0.891618,9.991159,1.048967,43.740941,0.352969,65.494453,...,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,97.621017,919.402894,0.065140,7113.550410,0.869943,9.996710,1.047753,43.707134,0.353145,65.585068,...,Success,NaN,1.453236e+06,17955.8936,122.063365,0.975361,0.029498,129.933354,3.201378,4.756716
30,97.660138,919.844301,0.064794,7042.829655,0.898967,9.938770,1.059125,43.755474,0.353054,65.494453,...,Success,NaN,1.454136e+06,17525.1046,121.991324,0.995457,0.030094,129.933354,0.590236,4.615187
31,97.667482,919.694791,0.064480,7042.829655,0.898210,9.974000,1.048218,43.729616,0.353064,65.494453,...,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,97.903035,919.463633,0.064597,7114.497424,0.870721,9.999461,1.060119,43.717158,0.353101,65.585068,...,Success,NaN,1.457478e+06,17843.8364,122.225771,0.963326,0.029050,129.933354,4.765173,4.719604
33,97.896816,919.696169,0.064772,7042.829655,0.893056,9.921065,1.047859,43.729616,0.353064,65.494453,...,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,97.890368,918.531637,0.064815,7042.814690,0.871627,9.999770,1.061477,43.718209,0.353157,65.503227,...,Success,NaN,1.456617e+06,17805.1104,122.286449,0.962714,0.029035,129.933354,4.844751,4.706827
35,97.924051,919.904840,0.064531,7118.821754,0.870483,9.997187,1.049191,42.714769,0.353125,65.621880,...,Success,NaN,1.458110e+06,17913.0026,122.228968,0.976997,0.029456,129.933354,2.988844,4.742487
36,97.855375,919.694791,0.064425,7042.949034,0.898374,9.998186,1.049956,43.754098,0.353064,65.494453,...,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,97.660138,919.844301,0.064776,7042.829655,0.898871,9.946523,1.059125,43.713604,0.353066,65.494453,...,Success,NaN,1.454136e+06,17529.3292,121.985068,0.995950,0.030109,129.933354,0.526166,4.616560
38,97.669876,919.694791,0.065410,7043.317167,0.899325,9.995369,1.055556,43.769641,0.352992,65.494453,...,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,97.660138,919.694791,0.064772,7042.829655,0.891951,9.946379,1.047911,43.729529,0.353066,65.494453,...,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,97.830803,919.863916,0.064370,7042.829548,0.897022,9.996172,1.052508,43.740216,0.353020,65.494453,...,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,97.610214,919.696195,0.064609,7114.497424,0.870730,9.999563,1.060119,43.722150,0.353059,65.603966,...,Success,NaN,1.453286e+06,17846.9737,121.864538,0.962174,0.029102,129.933354,4.914855,4.720640
42,97.777095,919.718626,0.064437,7120.039009,0.871542,9.968315,1.045678,43.752803,0.353181,65.603966,...,Success,NaN,1.455787e+06,17939.9217,122.012640,0.978971,0.029560,129.933354,2.732411,4.751414
43,97.621017,919.684704,0.064610,7041.773748,0.899617,9.991159,1.048967,43.740941,0.352969,65.494453,...,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,97.893037,919.904000,0.065374,7044.449457,0.871572,9.999346,1.049415,43.763470,0.353123,65.578468,...,Success,NaN,1.457647e+06,17916.6854,122.485379,0.976936,0.029464,129.933354,2.996789,4.743707
45,97.904062,919.696195,0.064597,7117.490152,0.870721,9.999844,1.060147,43.717158,0.353101,65.603966,...,Success,NaN,1.457661e+06,17844.4554,122.227054,0.963314,0.029049,129.933354,4.766703,4.719809
46,97.815629,919.812692,0.064790,7042.829655,0.897819,9.944934,1.054384,43.731357,0.353062,65.494453,...,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,97.893037,919.696195,0.065374,7044.449457,0.871572,9.999112,1.049415,43.763470,0.353059,65.578468,...,Success,NaN,1.457497e+06,17921.1521,122.485379,0.977133,0.029470,129.933354,2.971139,4.745188
48,97.901892,919.696195,0.064615,7040.245477,0.897293,9.986322,1.060145,43.774832,0.353059,65.494453,...,Success,NaN,1.457629e+06,17565.2116,122.230759,0.997011,0.030066,129.933354,0.388312,4.628233

In [15]:
df_optim = pd.read_csv("DAC_optimal_simulation_results_testing.csv")
df_optim.columns

Index(['caco3_flow_rate [kmol/hr]', 'calciner_temp [Deg C]',
       'pellet_moisture_frac', 'air_mol_flow_rate [kmol/hr]', 'RH_air',
       'DAC_column_height [m]', 'pellet_diameter [mm]',
       'DAC_ambient_temp [Deg C]', 'e_voidage', 'capture_efficiency_%',
       'SECC_$', 'Simulation_status', 'Failure_reason', 'Heat_duty[cal/sec]',
       'Brake_power[kW]', 'calcium_hydroxide_pellet[kmol_per_hr]',
       'SCM_conversion_fraction', 'Ca(OH)2_conversion',
       'mass_flow_co2_in[kg/hr]', 'mass_flow_co2_out[kg/hr]',
       'DAC_inlet_press[atm]'],
      dtype='object')

In [19]:
df_optim["SECC_$"]

0     10.950542
1     10.950542
2      7.172618
3      5.621132
4      3.874981
5      2.323490
6      7.172618
7      1.046576
8      3.874981
9      5.621132
10     2.123235
11     1.046576
12     2.323490
Name: SECC_$, dtype: float64

In [52]:
df_sim_results = pd.read_csv("DAC_simulation_results.csv")
#df_sim_results[df_sim_results["SCM_conversion_fraction"] > 0].sort_values(by="SCM_conversion_fraction", ascending=False)
df_sim_results.tail(30)

,caco3_flow_rate [kmol/hr],calciner_temp [Deg C],pellet_moisture_frac,air_mol_flow_rate [kmol/hr],RH_air,DAC_column_height [m],pellet_diameter [mm],DAC_ambient_temp [Deg C],e_voidage,sim_index,Simulation_status,Failure_reason,Heat_duty[cal/sec],Brake_power[kW],calcium_hydroxide_pellet[kmol_per_hr],SCM_conversion_fraction,Ca(OH)2_conversion,mass_flow_co2_in[kg/hr],mass_flow_co2_out[kg/hr],DAC_inlet_press[atm]
1070,97.168221,900.856253,0.190224,7788.506024,0.447167,4.215255,4.215585,29.214308,0.388035,1070.0,Success,NaN,1.433222e+06,4344.38391,158.708349,0.028194,0.000857,129.933354,126.270015,1.574627
1071,90.647216,914.015049,0.108440,8812.918594,0.564654,6.392935,1.961374,27.370128,0.431136,1071.0,Success,NaN,1.345820e+06,7980.58817,126.680204,0.127958,0.004168,129.933354,113.307371,2.191824
1072,25.796346,918.775035,0.240289,8949.452809,0.430063,3.097217,4.037014,18.441279,0.444325,1072.0,Success,NaN,3.838981e+05,2421.34293,45.158113,0.013546,0.001550,129.933354,128.173305,1.304308
1073,54.223119,945.203754,0.253156,8448.434588,0.172175,8.484204,2.409842,24.734290,0.386933,1073.0,Success,NaN,8.175278e+05,8930.75903,96.374100,0.063596,0.003463,129.933354,121.670050,2.378031
1074,72.712045,947.436594,0.290168,8589.325887,0.629979,8.265727,1.482146,27.667244,0.360145,1074.0,Success,NaN,1.097489e+06,14740.86630,134.288666,0.275234,0.011175,129.933354,94.171310,3.772536
1075,12.590563,907.422329,0.250577,8466.538188,0.473523,5.937127,3.068056,18.492058,0.431701,1075.0,Success,NaN,1.863180e+05,5355.25669,22.311727,0.027632,0.006479,129.933354,126.343063,1.731726
1076,8.528741,891.472428,0.061513,8054.794168,0.819203,8.640573,2.952510,40.604026,0.441842,1076.0,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1077,58.022260,896.788198,0.343162,8455.518279,0.584782,2.021474,5.244453,30.298233,0.350535,1077.0,Success,NaN,8.540868e+05,2805.98678,111.794318,0.013851,0.000705,129.933354,128.133651,1.355489
1078,64.592818,919.384739,0.235602,7785.223443,0.567087,1.311530,4.200956,28.046929,0.398108,1078.0,Success,NaN,9.615529e+05,1524.24680,112.421360,0.011226,0.000513,129.933354,128.474779,1.190327
1079,54.019635,930.916755,0.446082,7252.724137,0.862554,7.436926,1.958699,43.586013,0.445454,1079.0,Success,NaN,8.087541e+05,6898.40717,108.899964,0.168953,0.009234,129.933354,107.980766,1.992744
1080,14.005122,948.473371,0.164348,7070.234108,0.586832,8.774325,4.244362,44.665890,0.395399,1080.0,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1081,5.350647,897.674631,0.067437,7221.830303,0.128235,9.500279,4.488228,20.590247,0.374984,1081.0,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1082,19.973536,936.218572,0.233064,7532.029549,0.258126,8.832918,5.959984,27.223834,0.435303,1082.0,Success,NaN,2.998159e+05,3740.34591,34.652453,0.015425,0.002280,129.933354,127.929101,1.485778
1083,45.945498,917.554290,0.193536,8670.987856,0.145897,8.148283,3.908999,36.719892,0.429051,1083.0,Success,NaN,6.833417e+05,4891.40142,75.430095,0.028535,0.001834,129.933354,126.225661,1.658311
1084,10.376174,903.825931,0.078196,7037.736932,0.204813,9.950601,4.323924,29.010220,0.449868,1084.0,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1085,10.222322,913.659086,0.258779,8609.648287,0.589393,5.546032,1.792071,32.353046,0.419769,1085.0,Failure,"(-2147352567, 'Exception occurred.', (14, 'VAS...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1086,64.178292,918.466856,0.129724,7724.259110,0.418768,5.526063,2.980995,21.367724,0.389940,1086.0,Success,NaN,9.549477e+05,6506.38463,93.968350,0.051043,0.002348,129.933354,123.301205,1.923937
1087,54.898862,933.444531,0.442057,7477.791910,0.677181,3.182775,1.491350,24.429905,0.396534,1087.0,Success,NaN,8.229426e+05,7191.97530,110.570790,0.100105,0.005383,129.933354,116.926368,2.045411
1088,34.792418,938.106639,0.183285,8033.439621,0.427260,6.994927,1.504281,26.716264,0.397632,1088.0,Success,NaN,5.227427e+05,11387.86590,56.205904,0.117154,0.009941,129.933354,114.711111,2.911890
1089,98.133894,924.435177,0.272655,8006.864830,0.341550,7.351625,4.181561,38.469797,0.430476,1089.0,Success,NaN,1.464514e+06,4917.25402,178.150131,0.032232,0.000970,129.933354,125.745329,1.662343
1090,60.418605,934.051915,0.411379,7838.080944,0.880388,1.252209,2.895333,34.336218,0.425782,1090.0,Success,NaN,9.059556e+05,1324.69140,120.571052,0.032197,0.001573,129.933354,125.749945,1.165975
1091,57.519087,949.409831,0.462400,7244.484032,0.856765,3.999570,4.704334,41.947922,0.381682,1091.0,Success,NaN,8.690121e+05,3350.33266,116.307783,0.045506,0.002336,129.933354,124.020549,1.430353
1092,58.678881,921.771900,0.296766,7645.046416,0.270393,4.356912,4.150684,16.745218,0.370166,1092.0,Success,NaN,8.745490e+05,4570.13984,109.029017,0.019715,0.000992,129.933354,127.371738,1.608788
1093,29.486591,906.589971,0.171514,7428.009330,0.517300,7.511217,2.342548,17.476089,0.444586,1093.0,Success,NaN,4.361685e+05,6759.89419,46.713791,0.069798,0.006989,129.933354,120.864276,1.968234
1094,81.446084,892.487828,0.098118,7125.388836,0.867088,7.245197,5.302907,39.813865,0.430172,1094.0,Success,NaN,1.196311e+06,3313.91338,111.078907,0.076283,0.002765,129.933354,120.021618,1.425255
1095,50.419064,931.582229,0.154068,7646.329962,0.871272,2.471474,2.465906,36.134729,0.415279,1095.0,Success,NaN,7.550961e+05,3126.38350,77.436645,0.068118,0.003989,129.933354,121.082508,1.399205
1096,20.367716,905.685989,0.261500,7404.025181,0.680243,8.748796,2.436164,15.250342,0.353304,1096.0,Success,NaN,3.011457e+05,11104.27520,36.539915,0.102541,0.014864,129.933354,116.609830,2.846273
1097,13.269341,943.607141,0.311672,8443.948358,0.492100,5.956748,2.016575,34.602614,0.440534,1097.0,Success,NaN,1.999065e+05,7209.66759,24.973691,0.044639,0.009932,129.933354,124.133245,2.048617
1098,24.203261,930.235680,0.242999,8127.516368,0.417274,5.403669,4.581640,40.993224,0.449766,1098.0,Success,NaN,3.622370e+05,3344.08546,42.508663,0.017179,0.002096,129.933354,127.701165,1.429478
1099,41.747399,915.090332,0.400224,7659.011108,0.364127,6.059182,2.760015,29.408375,0.417007,1099.0,Success,NaN,6.201456e+05,6228.88590,82.950161,0.038539,0.002725,129.933354,124.925915,1.876271